name: "custom-action-test"
on:
  issues:
    types: [opened, edited, closed]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        cd javascript-action
        npm ci
        npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./custom-action
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
