name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
      working-directory: ${{ env.CURRENT_WORKSPACE }}/javascript-action
    - run: npm test
      working-directory: ${{ env.CURRENT_WORKSPACE }}/javascript-action

  # test action works running from the graph  
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./javascript-action
      with:
        milliseconds: 1000
